server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
logging:
  level: DEBUG
  loggers:
    co.charbot: TRACE
  appenders:
    - type: console