server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: logs/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: logs/access.%d.log.gz
        archivedFileCount: 14
# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG
  # Logger-specific levels.
  loggers:
    # Overrides the level of com.example.dw.Thing and sets it to DEBUG.
    "co.charbot": DEBUG
  appenders:
    # Log info, warnings and errors to our apps' main log.
    # Rolled over daily and retained for 5 days.
    - type: file
      threshold: INFO
      currentLogFilename: ./logs/info.log
      archivedLogFilenamePattern: ./logs/info-%d.log.gz
      archivedFileCount: 5

    # Log debug messages, info, warnings and errors to our apps' debug log.
    # Rolled over hourly and retained for 6 hours
    - type: file
      threshold: DEBUG
      currentLogFilename: ./logs/debug.log
      archivedLogFilenamePattern: ./logs/debug-%d{yyyy-MM-dd-hh}.log.gz
      archivedFileCount: 6